### Вычисления с помощью Numpy

##### Номер 1

In [1]:
import numpy as np

In [2]:
a = np.array([[1, 6],
              [2, 8],
              [3, 11],
              [3, 10],
              [1, 7]])

In [3]:
mean_a = a.mean(axis = 0)

In [4]:
mean_a

array([2. , 8.4])

In [5]:
a.shape

(5, 2)

##### Номер 2

In [7]:
a_centered = a - mean_a

In [8]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [10]:
a_centered.shape

(5, 2)

##### Номер 3

In [ ]:
a_centered_sp = a_centered[0:, 0] @ a_centered[0:, 1]

In [13]:
a_centered_sp

8.0

In [14]:
a_centered_sp.shape

()

In [15]:
print(a_centered_sp / (5 - 1))

2.0


##### Номер 4

In [18]:
m = a.T

In [19]:
m

array([[ 1,  2,  3,  3,  1],
       [ 6,  8, 11, 10,  7]])

In [20]:
np.cov(m)

array([[1. , 2. ],
       [2. , 4.3]])

Замечание: np.cov(m)[0][1] == a_centered_sp / (5 - 1)

### Работа с данными в Pandas

In [6]:
import pandas as pd

##### Номер 1

In [86]:
authors = pd.DataFrame({
    'author_id': [1, 2, 3],
    'author_name': ['Тургенев', 'Чехов', 'Островский']
})

authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [87]:
book = pd.DataFrame({
    'author_id': [1, 1, 1, 2, 2, 3, 3],
    'book_title': ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 
                   'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
    'price': [450, 300, 350, 500, 450, 370, 290]
})

book

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

##### Номер 2

In [88]:
authors_price = pd.merge(authors, book, on='author_id', how='inner')
    
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

##### Номер 3

In [93]:
top5 = authors_price.sort_values(by='price')

top5['book_title'].tail()

2    Дворянское гнездо
5                Гроза
0          Отцы и дети
4      Дама с собачкой
3     Толстый и тонкий
Name: book_title, dtype: object

##### Номер 4

In [83]:
authors_stat = pd.DataFrame({
    'min_price': authors_price.groupby('author_name')['price'].min(),
    'max_price': authors_price.groupby('author_name')['price'].max(),
    'mean_price': authors_price.groupby('author_name')['price'].mean()
})

authors_stat

min_price  max_price  mean_price
author_name                                  
Островский         290        370  330.000000
Тургенев           300        450  366.666667
Чехов              450        500  475.000000

##### Номер 5

In [96]:
authors_price['cover'] = ['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']

In [97]:
?pd.pivot_table

In [98]:
import numpy as np

In [114]:
 book_info = pd.pivot_table(authors_price,
                           values='price',
                    index=['author_name'],
                        columns=['cover'],
                           aggfunc=np.sum,
                             fill_value=0)
    
 book_info

cover        мягкая  твердая
author_name                 
Островский      660        0
Тургенев        650      450
Чехов             0      950

In [116]:
book_info.to_pickle('book_info.pk')

In [120]:
book_info2 = pd.read_pickle('book_info.pk')

book_info2

cover        мягкая  твердая
author_name                 
Островский      660        0
Тургенев        650      450
Чехов             0      950